import test from "node:test";
import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import { stripTypeScriptTypes } from "node:module";
import vm from "node:vm";
const root = new URL("../", import.meta.url);
const read = path => readFile(new URL(path, root), "utf8");
const manifest = JSON.parse(await read("manifest.json"));

test("MV3 references real files; experimental script is not unconditionally injected", async () => {
  assert.equal(manifest.manifest_version, 3);
  assert.equal(manifest.minimum_chrome_version, "120");
  for (const path of [manifest.background.service_worker, manifest.action.default_popup,
    ...manifest.content_scripts.flatMap(script => script.js),
    ...manifest.declarative_net_request.rule_resources.map(rule => rule.path)]) {
    assert.ok((await read(path)).length);
  }
  assert.ok(!manifest.content_scripts.some(script => script.js.includes("dist/youtube.js")));
  assert.ok(!manifest.permissions.includes("declarativeNetRequestFeedback"));
});
test("all committed JS is built from TypeScript, not manually maintained", async () => {
  for (const file of await readdir(new URL("src/", root))) {
    if (!file.endsWith(".ts")) continue;
    const expected = "// Generated by npm run build; edit src/ instead.\n" +
      stripTypeScriptTypes(await read("src/" + file), { mode: "strip" });
    assert.equal(await read("dist/" + file.replace(/\.ts$/, ".js")), expected);
  }
});
test("content scripts parse as classic scripts", async () => {
  for (const path of ["dist/content.js", "dist/youtube.js"]) new vm.Script(await read(path));
});
test("starter rules use unique IDs and do not block YouTube media domains", async () => {
  const rules = JSON.parse(await read("rules/core.json"));
  assert.equal(new Set(rules.map(rule => rule.id)).size, rules.length);
  for (const rule of rules) {
    assert.equal(rule.action.type, "block");
    assert.ok(rule.priority < 100);
    assert.ok(!rule.condition.urlFilter.includes("youtube.com"));
    assert.ok(!rule.condition.urlFilter.includes("googlevideo.com"));
    assert.ok(!rule.condition.resourceTypes.includes("main_frame"));
  }
});
