import test from "node:test";
import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import { stripTypeScriptTypes } from "node:module";
import vm from "node:vm";
import { FILES } from "../scripts/package.mjs";
const root = new URL("../", import.meta.url);
const read = path => readFile(new URL(path, root), "utf8");
const manifest = JSON.parse(await read("manifest.json"));

test("MV3 references real files; experimental script is not unconditionally injected", async () => {
  assert.equal(manifest.manifest_version, 3);
  assert.equal(manifest.minimum_chrome_version, "120");
  for (const path of [manifest.background.service_worker, manifest.action.default_popup,
    ...(manifest.content_scripts ?? []).flatMap(script => script.js),
    ...manifest.declarative_net_request.rule_resources.map(rule => rule.path)]) {
    assert.ok((await read(path)).length);
  }
  assert.equal(manifest.content_scripts, undefined);
  assert.equal(manifest.host_permissions, undefined);
  assert.ok(!manifest.permissions.includes("declarativeNetRequestFeedback"));
});
test("toolbar icons exist, match the manifest, and are in the ZIP inventory", async () => {
  const paths = [...new Set([...Object.values(manifest.icons), ...Object.values(manifest.action.default_icon)])];
  assert.deepEqual(paths.sort(), ["icons/icon128.png", "icons/icon16.png", "icons/icon32.png", "icons/icon48.png"]);
  for (const path of paths) {
    assert.ok(FILES.includes(path), path);
    assert.ok((await readFile(new URL(path, root))).length > 0);
  }
});
test("all committed JS is built from TypeScript, not manually maintained", async () => {
  for (const file of await readdir(new URL("src/", root))) {
    if (!file.endsWith(".ts")) continue;
    const expected = "// Generated by npm run build; edit src/ instead.\n" +
      stripTypeScriptTypes(await read("src/" + file), { mode: "strip" });
    assert.equal(await read("dist/" + file.replace(/\.ts$/, ".js")), expected);
  }
});
test("content scripts parse as classic scripts", async () => {
  for (const path of ["dist/content.js", "dist/youtube.js"]) new vm.Script(await read(path));
});
test("starter rules use unique IDs, host-only filters, and do not block YouTube media domains", async () => {
  const rules = JSON.parse(await read("rules/core.json"));
  assert.equal(rules.length, 24);
  assert.equal(new Set(rules.map(rule => rule.id)).size, rules.length);
  const hosts = new Set();
  for (const rule of rules) {
    assert.equal(rule.action.type, "block");
    assert.ok(rule.priority < 100);
    assert.match(rule.condition.urlFilter, /^\|\|[a-z0-9.-]+\^$/);
    assert.equal(hosts.has(rule.condition.urlFilter), false);
    hosts.add(rule.condition.urlFilter);
    assert.ok(!rule.condition.urlFilter.includes("youtube.com"));
    assert.ok(!rule.condition.urlFilter.includes("googlevideo.com"));
    assert.ok(!rule.condition.urlFilter.includes("ytimg.com"));
    assert.ok(!rule.condition.urlFilter.includes("gstatic.com"));
    assert.ok(!rule.condition.urlFilter.includes("googleapis.com"));
    assert.ok(!rule.condition.resourceTypes.includes("main_frame"));
    assert.ok(!rule.condition.resourceTypes.includes("media"));
    assert.deepEqual(rule.condition.resourceTypes, ["script", "image", "xmlhttprequest", "sub_frame"]);
  }
});
