// Dependency-free TypeScript erasure. Type checking remains a separate tsc command.
import { stripTypeScriptTypes } from "node:module";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
const root = new URL("../", import.meta.url);
await mkdir(new URL("dist/", root), { recursive: true });
for (const file of (await readdir(new URL("src/", root))).sort()) {
  if (!file.endsWith(".ts")) continue;
  const source = await readFile(new URL("src/" + file, root), "utf8");
  const output = stripTypeScriptTypes(source, { mode: "strip" });
  await writeFile(new URL("dist/" + file.replace(/\.ts$/, ".js"), root),
    "// Generated by npm run build; edit src/ instead.\n" + output);
}
console.log("Built TypeScript sources into dist/.");
